
project_id = "huakzwguwjulxhvcztuh"

[functions.get-producer-report]
verify_jwt = true

[functions.get-producer-products]
verify_jwt = true

[functions.get-or-create-iugu-customer]
verify_jwt = false

[functions.create-iugu-payment-token]
verify_jwt = false

[functions.create-iugu-transaction]
verify_jwt = false

[functions.payment-webhook-handler]
verify_jwt = false

[functions.get-producer-financials]
verify_jwt = true

[functions.get-withdrawal-history]
verify_jwt = true

[functions.request-withdrawal]
verify_jwt = true

[functions.get-all-withdrawal-requests]
verify_jwt = true

[functions.process-withdrawal-request]
verify_jwt = true

[functions.release-security-reserves]
verify_jwt = false

[functions.update-user-profile]
verify_jwt = true
