
project_id = "huakzwguwjulxhvcztuh"

[functions.get-or-create-iugu-customer]
verify_jwt = false

[functions.create-iugu-payment-token]
verify_jwt = false

[functions.create-iugu-transaction]
verify_jwt = false
