
project_id = "huakzwguwjulxhvcztuh"

[functions.get-or-create-iugu-customer]
verify_jwt = false

[functions.create-iugu-payment-token]
verify_jwt = false

[functions.create-iugu-transaction]
verify_jwt = false

[functions.payment-webhook-handler]
verify_jwt = false

[functions.tokenize-card]
verify_jwt = false
